name: pdf-compile
on:
    workflow_dispatch:
    pull_request:
jobs:
    pdf-compile:
        runs-on: ubuntu-latest
        container: aergus/latex:latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: PDF compile
              run: latexmk thesis.tex printable-thesis.tex

name: Spellcheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Spellcheck
        uses: streetsidesoftware/cspell-action@v5
        with:
          files: "**/*.tex"
          config: ".cspell.json"